### PR TITLE
config: enable hold and wip for tikv pd repo

### PR DESCRIPTION
**Pull request by hi-rustin**
enable hold and wip for tikv pd repo.

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold 

Waiting pd team @nolouch  @rleungx approve.

The plugins docs:

[hold](https://book.prow.tidb.io/plugins/hold.html)

[wip](https://book.prow.tidb.io/plugins/wip.html)

**Review by rleungx — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold cancel

/assign @Mini256 

PTAL~ Thanks!

**Pull request merged**
