### PR TITLE
style: update color scheme of labels

### PR DESCRIPTION
**Pull request by AstroProfundis**
Update color scheme of labels to make them more distinguishable.

### CODE REVIEW

**Comment by hi-rustin** [comment]
@AstroProfundis  Thanks for your contribution.

Could you please show the color changes you made with pictures?

**Comment by AstroProfundis** [comment]
图片
Something like this

**Comment by AstroProfundis** [comment]
The current color is like this:
图片
and this:
图片
and making me blind.

**Comment by hi-rustin** [comment]
I want the hold,wip,needs-rebase to be red.

Also, in tidb or tikv, or many other repositories, everyone uses one color for the same type, so I think maybe we shouldn't bother changing the color of the same type?

@lucklove @Mini256  What do you think?

**Comment by AstroProfundis** [comment]
The VERY REASON I opened this PR is because all tags in the same type shares the same color, which makes it very difficult to distinguish them in the issue list.

A second reason is that those colors we use now is too bright and saturation too high, which makes my eyes tired quickly and going to be blind.

See my second comment for the screenshot it is now.

**Comment by AstroProfundis** [comment]
> everyone uses one color for the same type

They might be too busy that don't yet have time to read dozens of issues in one afternoon.

**Comment by hi-rustin** [comment]
> They might be too busy that don't yet have time to read dozens of issues in one afternoon.

🤣

**Comment by Mini256** [comment]
Maybe we can write a program to preview the effect of the label color？

**Comment by hi-rustin** [comment]
> Maybe we can write a program to preview the effect of the label color？
It would be nice to have.

**Comment by AstroProfundis** [comment]
and here's the red (pink actually) hold, wip and rebase
图片

**Comment by AstroProfundis** [comment]
I'm using this simple HTML template to take the screenshot, FYI
`<!DOCTYPE html>
<html>
<head>
<style>
.button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

.size-xs {background-color: #83e377; color: black;}
.size-s {background-color: #b9e769; color: black;}
.size-m {background-color: #efea5a; color: black;}
.size-l{background-color: #f1c453; color: black;}
.size-xl{background-color: #f29e4c;}
.size-xxl{background-color: #f1673a;}

.status-lgt1{background-color: #93ca8c; color: black;}
.status-lgt2{background-color: #87c47e; color: black;}
.status-lgt3{background-color: #7abe71;}
.status-lgt4{background-color: #6db864;}
.status-canmerge{background-color: #55a630;}

.status-discuss{background-color: #2a9d8f;}
.status-invest{background-color: #cdd993; color: black;}
.status-doc{background-color: #f2e8cf; color: black;}
.status-info{background-color: #7e8e7f;}
.status-todo{background-color: #887593;}
.status-wontfix{background-color: #e2e2df; color: black;}

.donot-merge-hold{background-color: #ffc2d4; color: black;}
.donot-merge-wip{background-color: #ff9ebb; color: black;}

.needs-rebase{background-color: #ff7aa2; color: black;}
.help-wanted{background-color: #ffdd00; color: black;}
.good-first{background-color: #97b6ff;}

.cat-doc{background-color: #045780;}
.cat-sec{background-color: #cfc1b2; color: black;}
.cat-sta{background-color: #252e3e;}
.cat-test{background-color: #3e7c93;}
.cat-use{background-color: #527c7d;}

.diff-easy{background-color: #e2eafc; color: black;}
.diff-mid{background-color: #ccdbfd; color: black;}
.diff-hard{background-color: #b6ccfe; color: black;}

.pri-p0{background-color: #ff7b00;}
.pri-p1{background-color: #ffa200; color: black;}
.pri-p2{background-color: #ffc300; color: black;}

.type-bug{background-color: #ef959d; color: black;}
.type-dupe{background-color: #e2cfc4; color: black;}
.type-enhance{background-color: #c6def1; color: black;}
.type-freq{background-color: #69585f;}
.type-newf{background-color: #c9e4de; color: black;}
.type-ques{background-color: #dbcdf0; color: black;}
</style>
</head>
<body>

<h2>Label Color Examples</h2>
<p>Common labels</p>
<button class="button size-xs">size/XS</button>
<button class="button size-s">size/S</button>
<button class="button size-m">size/M</button>
<button class="button size-l">size/L</button>
<button class="button size-xl">size/XL</button>
<button class="button size-xxl">size/XXL</button>
<br />
<button class="button status-lgt1">status/LGT1</button>
<button class="button status-lgt2">status/LGT2</button>
<button class="button status-lgt3">status/LGT3</button>
<button class="button status-lgt4">status/LGT4</button>
<button class="button status-canmerge">status/can-merge</button>
<br />
<button class="button donot-merge-hold">do-not-merge/hold</button>
<button class="button donot-merge-wip">do-not-merge/work-in-progress</button>
<br />
<button class="button needs-rebase">needs-rebase</button>
<button class="button help-wanted">help wanted</button>
<button class="button good-first">good first issue</button>
<p>TiUP labels</p>
<button class="button cat-doc">category/document</button>
<button class="button cat-sec">category/security</button>
<button class="button cat-sta">category/stability</button>
<button class="button cat-test">category/testing</button>
<button class="button cat-use">category/usability</button>
<br />
<button class="button diff-easy">difficulty/easy</button>
<button class="button diff-mid">difficulty/medium</button>
<button class="button diff-hard">difficulty/hard</button>
<br />
<button class="button pri-p0">priority/P0</button>
<button class="button pri-p1">priority/P1</button>
<button class="button pri-p2">priority/P2</button>
<br />
<button class="button status-discuss">status/discuss</button>
<button class="button status-invest">status/investigating</button>
<button class="button status-doc">status/need-doc</button>
<button class="button status-info">status/need-info</button>
<button class="button status-todo">status/TODO</button>
<button class="button status-wontfix">status/wontfix</button>
<br />
<button class="button type-bug">type/bug</button>
<button class="button type-dupe">type/duplicate</button>
<button class="button type-enhance">type/enhancement</button>
<button class="button type-freq">type/feature-request</button>
<button class="button type-newf">type/new-feature</button>
<button class="button type-ques">type/question</button>
</body>
</html>
`

**Comment by hi-rustin** [comment]
> and here's the red (pink actually) hold, wip and rebase tag you ordered
> 图片

I like the colors, but these changes would have to be agreed to by  @rleungx @nolouch as well.

This is because these labels are the default labels for all repositories.

BTW, what is this tool you are using?

**Comment by AstroProfundis** [comment]
I'm using https://coolors.co and http://colormind.io/template/paper-dashboard/ to find / generate useful color palettes, and using https://www.colorhexa.com to help adjusting.

**Comment by hi-rustin** [comment]
/hold 

Waiting pd team (@rleungx @nolouch ) approve.

Waiting tiup team (@lucklove ) approve.

**Comment by rleungx** [comment]
I don't think this is a good idea, which makes the label messy.

**Comment by HunDunDM** [comment]
> A second reason is that those colors we use now is too bright and saturation too high, which makes my eyes tired quickly and going to be blind.

I agree. I think this part of the change can be implemented first.

**Comment by JmPotato** [comment]
The color of a label itself will contain some information for the reader, for example, if several labels have the same color, it indicates that they are in the same category, which can reduce the reaction time we need to distinguish them. However, if the color of labels is different from each other. It will reduce the amount of information it carries, and also need us to know its meaning by reading the label text, which I think will against the original intention we want.

**Comment by hi-rustin** [comment]
> I think this part of the change can be implemented first.

I agree.

**Comment by AstroProfundis** [comment]
> if several labels have the same color, it indicates that they are in the same category, which can reduce the reaction time we need to distinguish them

if several labels have the same color, it indicates that they are the same label, which can increase the reaction time we need to distinguish them

图片

Which of these issues are bug and which are feature requests? How can I distinguish them without measuring their length?

**Comment by AstroProfundis** [comment]
There is a simple fact that, human notices color earlier than text, if the labels can not distinguish each other by color, it takes more attention to distinguish them by reading text.

And don't bother to read multiple tag texts starting with the same prefix, we just spend no more than several tiny seconds to understand they are actually different labels.

**Comment by AstroProfundis** [comment]
BTW, I totally don't understand the idea to keep labels "sorted" or "ordered"

-- are you guys using labels to distinguish different issues, like people do when tagging their drafts and notebooks, or are you just trying to make the issue list page more like a printed handbook or dictionary index?

It's nature to use different color for tagging if you want to distinguish things other than archive them.

**Comment by AstroProfundis** [comment]
So what's now?

**Comment by hi-rustin** [comment]
> So what's now?

Because we currently have fewer deployed repositories, can we first change the label color to a non-blinding color as a first step, and after we deploy for tidb/tikv, I will open a document to discuss this issue and eventually vote to solve the problem, what do you think?

**Comment by AstroProfundis** [comment]
I don't care about other repos at all, I only care about my own eyes, so anything that can make labels in tiup repo not hurting my eyes anymore is welcomed.

**Comment by AstroProfundis** [comment]
And:

> There is no way to persuade me using one color for multiple tags.

**Comment by AstroProfundis** [comment]
Anyway, I have manually updated the label colors in tiup repo, take your time playing the one-vote veto game.
图片

And feel free to compare it with the screenshots of former color scheme above.

**Comment by hi-rustin** [comment]
/close 

close by https://github.com/tidb-community-bots/configs/pull/53

**Pull request closed without merging**
