### PR TITLE
config: enable bot for pingcap/tidb-operator

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold 

- [ ] Waiting k8s team review
- [ ] Waiting @sykp241095 update bot permission for pingcap/tidb-operator
- [ ] Waiting @AndreMouche  stop the ti-srebot lgtm and megre

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
cc: @AstroProfundis @lonng @july2993

PTAL~

**Review by sykp241095 — APPROVED** [review]
/LGTM

**Comment by hi-rustin** [comment]
/hold cancel

All approved.

**Comment by hi-rustin** [comment]
> @hi-rustin: Updated the following 3 configmaps:
> 
>     * `plugins` configmap in namespace `prow` at cluster `default` using the following files:
>       
>       * key `plugins.yaml` using file `prow/config/plugins.yaml`
> 
>     * `config` configmap in namespace `prow` at cluster `default` using the following files:
>       
>       * key `config.yaml` using file `prow/config/config.yaml`
> 
>     * `external-plugins-config` configmap in namespace `prow` at cluster `default` using the following files:
>       
>       * key `external_plugins_config.yaml` using file `prow/config/external_plugins_config.yaml`

@DanielZhangQD  Already deployed.

**Pull request merged**
